#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

/** @var Application $application */
$application = require __DIR__ . '/console-application.php';
$application->run(new ArgvInput());
